#ifndef msavi_h
#define msavi_h

#include "msfilter.h"

typedef enum {
    AVI_STATE_NONE=0,
    AVI_STATE_INIT,
    AVI_STATE_OPEN,
    AVI_STATE_START,
    AVI_STATE_STOP,
    AVI_STATE_CLOSE,
}AviState_t;

typedef struct
{
    char *filename;
    int width;
    int height;
    double framerate;
} AviParam_t;


/*methods*/
//#define MS_AVI_WRITE_OPEN	MS_FILTER_METHOD(MS_AVI_H264_ID,0,char*)
#define MS_AVI_WRITE_OPEN	MS_FILTER_METHOD(MS_AVI_H264_ID, 0, AviParam_t *)
#define MS_AVI_WRITE_CLOSE 	MS_FILTER_METHOD_NO_ARG(MS_AVI_H264_ID,1)
#define MS_AVI_WRITE_START	MS_FILTER_METHOD_NO_ARG(MS_AVI_H264_ID,2)
#define MS_AVI_WRITE_STOP	MS_FILTER_METHOD_NO_ARG(MS_AVI_H264_ID,3)
#define MS_AVI_WRITE_SET_DURATION	MS_FILTER_METHOD(MS_AVI_H264_ID,4, int*)

#define MS_AVI_WRITE_OPEN_AU	MS_FILTER_METHOD(MS_AVI_G711_ID,0,char*)
#define MS_AVI_WRITE_CLOSE_AU 	MS_FILTER_METHOD_NO_ARG(MS_AVI_G711_ID,1)
#define MS_AVI_WRITE_START_AU	MS_FILTER_METHOD_NO_ARG(MS_AVI_G711_ID,2)
#define MS_AVI_WRITE_STOP_AU	MS_FILTER_METHOD_NO_ARG(MS_AVI_G711_ID,3)
#define MS_AVI_WRITE_START_NOOPEN MS_FILTER_METHOD_NO_ARG(MS_AVI_G711_ID,4)

#define MS_AVI_READ_OPEN	MS_FILTER_METHOD(MS_AVI_READ_ID,0,char*)
#define MS_AVI_READ_CLOSE 	MS_FILTER_METHOD_NO_ARG(MS_AVI_READ_ID,1)
#define MS_AVI_READ_START	MS_FILTER_METHOD_NO_ARG(MS_AVI_READ_ID,2)
#define MS_AVI_READ_STOP	MS_FILTER_METHOD_NO_ARG(MS_AVI_READ_ID,3)


//Events
#define MS_AVI_READ_EOF	MS_FILTER_EVENT_NO_ARG(MS_AVI_READ_ID,0)

#endif
