#ifndef waveplayfilter_h
#define waveplayfilter_h

#include "msfilter.h"


/*methods*/
#define MS_WAVE_PLAY_FILTER_OPEN MS_FILTER_METHOD(MS_WAVE_PLAY_FILTER_ID,0,const char*)
#define MS_WAVE_PLAY_FILTER_START MS_FILTER_METHOD(MS_WAVE_PLAY_FILTER_ID,1,const char*)
#define MS_WAVE_PLAY_FILTER_STOP	MS_FILTER_METHOD_NO_ARG(MS_WAVE_PLAY_FILTER_ID,2)
#define MS_WAVE_PLAY_FILTER_CLOSE	MS_FILTER_METHOD_NO_ARG(MS_WAVE_PLAY_FILTER_ID,3)

#define MS_WAVE_PLAY_FILTER_DONE	MS_FILTER_METHOD(MS_WAVE_PLAY_FILTER_ID,4,int)

#define MS_WAVE_PLAY_FILTER_INTERR	MS_FILTER_METHOD(MS_WAVE_PLAY_FILTER_ID,5,int)
#define MS_WAVE_PLAY_FILTER_LOOP	MS_FILTER_METHOD(MS_WAVE_PLAY_FILTER_ID,6,int)
 
/*events*/
#define MS_WAVE_PLAY_FILTER_EOF	MS_FILTER_EVENT_NO_ARG(MS_WAVE_PLAY_FILTER_ID,0)

#endif
