/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_tgt_device_manager_remote_RemoteVSIMService */

#ifndef _Included_com_tgt_device_manager_remote_RemoteVSIMService
#define _Included_com_tgt_device_manager_remote_RemoteVSIMService
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_tgt_device_manager_remote_RemoteVSIMService
 * Method:    GetVSIMVersion
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_tgt_device_manager_remote_RemoteVSIMService_GetVSIMVersion
  (JNIEnv *, jobject);

/*
 * Class:     com_tgt_device_manager_remote_RemoteVSIMService
 * Method:    VSIMSendSIMData
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;ILjava/lang/String;I)I
 */
JNIEXPORT jint JNICALL Java_com_tgt_device_manager_remote_RemoteVSIMService_VSIMSendSIMData
  (JNIEnv *, jobject, jstring, jstring, jstring, jstring, jstring, jstring, jint, jstring, jint);

/*
 * Class:     com_tgt_device_manager_remote_RemoteVSIMService
 * Method:    VSIMUpdateStatus
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_com_tgt_device_manager_remote_RemoteVSIMService_VSIMUpdateStatus
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     com_tgt_device_manager_remote_RemoteVSIMService
 * Method:    VSIMStart
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_tgt_device_manager_remote_RemoteVSIMService_VSIMStart
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_tgt_device_manager_remote_RemoteVSIMService
 * Method:    VSIMStop
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_tgt_device_manager_remote_RemoteVSIMService_VSIMStop
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_tgt_device_manager_remote_RemoteVSIMService
 * Method:    VSIMSendSignal
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_tgt_device_manager_remote_RemoteVSIMService_VSIMSendSignal
  (JNIEnv *, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
