/*****************************************************************************
*  Copyright Statement:
*  --------------------
*  This software is protected by Copyright and the information contained
*  herein is confidential. The software may not be copied and the information
*  contained herein may not be used or disclosed except with the written
*  permission of TGT Limited. (C) 2016
*
*  BY OPENING THIS FILE, BUYER HEREBY UNEQUIVOCALLY ACKNOWLEDGES AND AGREES
*  THAT THE SOFTWARE/FIRMWARE AND ITS DOCUMENTATIONS ("TGT SOFTWARE")
*  RECEIVED FROM TGT AND/OR ITS REPRESENTATIVES ARE PROVIDED TO BUYER ON
*  AN "AS-IS" BASIS ONLY. TGT EXPRESSLY DISCLAIMS ANY AND ALL WARRANTIES,
*  EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE IMPLIED WARRANTIES OF
*  MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE OR NONINFRINGEMENT.
*  NEITHER DOES TGT PROVIDE ANY WARRANTY WHATSOEVER WITH RESPECT TO THE
*  SOFTWARE OF ANY THIRD PARTY WHICH MAY BE USED BY, INCORPORATED IN, OR
*  SUPPLIED WITH THE TGT SOFTWARE, AND BUYER AGREES TO LOOK ONLY TO SUCH
*  THIRD PARTY FOR ANY WARRANTY CLAIM RELATING THERETO. TGT SHALL ALSO
*  NOT BE RESPONSIBLE FOR ANY TGT SOFTWARE RELEASES MADE TO BUYER'S
*  SPECIFICATION OR TO CONFORM TO A PARTICULAR STANDARD OR OPEN FORUM.
*
*  BUYER'S SOLE AND EXCLUSIVE REMEDY AND TGT'S ENTIRE AND CUMULATIVE
*  LIABILITY WITH RESPECT TO THE TGT SOFTWARE RELEASED HEREUNDER WILL BE,
*  AT TGT'S OPTION, TO REVISE OR REPLACE THE TGT SOFTWARE AT ISSUE,
*  OR REFUND ANY SOFTWARE LICENSE FEES OR SERVICE CHARGE PAID BY BUYER TO
*  TGT FOR SUCH TGT SOFTWARE AT ISSUE. 
*
*  THE TRANSACTION CONTEMPLATED HEREUNDER SHALL BE CONSTRUED IN ACCORDANCE
*  WITH THE LAWS OF THE STATE OF CALIFORNIA, USA, EXCLUDING ITS CONFLICT OF
*  LAWS PRINCIPLES.  ANY DISPUTES, CONTROVERSIES OR CLAIMS ARISING THEREOF AND
*  RELATED THERETO SHALL BE SETTLED BY ARBITRATION IN SAN FRANCISCO, CA, UNDER
*  THE RULES OF THE INTERNATIONAL CHAMBER OF COMMERCE (ICC).
*
*****************************************************************************/

/*****************************************************************************
 *
 * Filename: softsim_macro.h
 *
 * Description:
 *
 * Author:chuan.mei
 * 
 * Date: 2016-07-08
 ******************************************************************************/

#ifndef __SOFTSIM_MACRO_H__
#define __SOFTSIM_MACRO_H__

/*VERSION MACRO*/
#define __SOFTSIM_ALPHA_VERSION__
//#define __SOFTSIM_BETA_VERSION__
//#define __SOFTSIM__RELEASE_VERSION__

/*ENVIRONMENT&PLATFORM MACRO*/
//#define __SOFTSIM_LINUX__			/*Linux*/
#define __SOFTSIM_ANDROID__			/*Android*/

/*PRODUCT&PROJECT MACRO*/
#define __SOFTSIM_T2C__
//#define __SOFTSIM_T3__

/*FEATURE MACRO*/
//#define __SOFTSIM_EXECUTABLE__

#if defined(__SOFTSIM_ANDROID__)
//#define __SOFTSIM_ANDROID_TRACE__
#define __SOFTSIM_TRACE__
#define __SOFTSIM_MONITOR__

	#if defined(__SOFTSIM_MONITOR__)
		//#define __SOFTSIM_HEARTBEAT__
	#endif
#else
#define __SOFTSIM_TRACE__
#endif

#define __SOFTSIM_ISO_7816_DATA_TRACE__
//#define __UICC_DATA_TRACE__
//#define __AUTH_DATA_TRACE__

#define __SOFTSIM_INFO__
//#define __SOFTSIM_SOCKET_INTERFACE_NAME__
#define __SOFTSIM_CHANNEL_SPECIFIED__
//#define __SOFTSIM_TEST__
//#define __SOFTSIM_AUTH_DEMO__

#define __SOFTSIM_REMOTE_SIM__
//#define __SOFTSIM_LOCAL_SIM__

#if defined(__SOFTSIM_LOCAL_SIM__)
//#define SOFTSIM_0
//#define SOFTSIM_1
//#define SOFTSIM_2
//#define SOFTSIM_3
#define SOFTSIM_4
#endif

#endif /*__SOFTSIM_MACRO_H__*/
