/*****************************************************************************
*  Copyright Statement:
*  --------------------
*  This software is protected by Copyright and the information contained
*  herein is confidential. The software may not be copied and the information
*  contained herein may not be used or disclosed except with the written
*  permission of TGT Limited. (C) 2016
*
*  BY OPENING THIS FILE, BUYER HEREBY UNEQUIVOCALLY ACKNOWLEDGES AND AGREES
*  THAT THE SOFTWARE/FIRMWARE AND ITS DOCUMENTATIONS ("TGT SOFTWARE")
*  RECEIVED FROM TGT AND/OR ITS REPRESENTATIVES ARE PROVIDED TO BUYER ON
*  AN "AS-IS" BASIS ONLY. TGT EXPRESSLY DISCLAIMS ANY AND ALL WARRANTIES,
*  EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE IMPLIED WARRANTIES OF
*  MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE OR NONINFRINGEMENT.
*  NEITHER DOES TGT PROVIDE ANY WARRANTY WHATSOEVER WITH RESPECT TO THE
*  SOFTWARE OF ANY THIRD PARTY WHICH MAY BE USED BY, INCORPORATED IN, OR
*  SUPPLIED WITH THE TGT SOFTWARE, AND BUYER AGREES TO LOOK ONLY TO SUCH
*  THIRD PARTY FOR ANY WARRANTY CLAIM RELATING THERETO. TGT SHALL ALSO
*  NOT BE RESPONSIBLE FOR ANY TGT SOFTWARE RELEASES MADE TO BUYER'S
*  SPECIFICATION OR TO CONFORM TO A PARTICULAR STANDARD OR OPEN FORUM.
*
*  BUYER'S SOLE AND EXCLUSIVE REMEDY AND TGT'S ENTIRE AND CUMULATIVE
*  LIABILITY WITH RESPECT TO THE TGT SOFTWARE RELEASED HEREUNDER WILL BE,
*  AT TGT'S OPTION, TO REVISE OR REPLACE THE TGT SOFTWARE AT ISSUE,
*  OR REFUND ANY SOFTWARE LICENSE FEES OR SERVICE CHARGE PAID BY BUYER TO
*  TGT FOR SUCH TGT SOFTWARE AT ISSUE. 
*
*  THE TRANSACTION CONTEMPLATED HEREUNDER SHALL BE CONSTRUED IN ACCORDANCE
*  WITH THE LAWS OF THE STATE OF CALIFORNIA, USA, EXCLUDING ITS CONFLICT OF
*  LAWS PRINCIPLES.  ANY DISPUTES, CONTROVERSIES OR CLAIMS ARISING THEREOF AND
*  RELATED THERETO SHALL BE SETTLED BY ARBITRATION IN SAN FRANCISCO, CA, UNDER
*  THE RULES OF THE INTERNATIONAL CHAMBER OF COMMERCE (ICC).
*
*****************************************************************************/


/*****************************************************************************
 *
 * Filename: softsim_enum.h
 *
 * Description:
 *
 * Author: chuan.mei
 * 
 * Date: 2016-07-16
 ******************************************************************************/
#ifndef __SOFTSIM_ENUM_H__
#define __SOFTSIM_ENUM_H__

#ifdef __cplusplus
extern "C"{
#endif

typedef enum
{
	SOFTSIM_SLOT_1,
	SOFTSIM_SLOT_2,
	SOFTSIM_SLOT_3,
	SOFTSIM_SLOT_MAX,
	SOFTSIM_SLOT_END=0xff,
}SoftsimSlot;

typedef enum
{
	SOFTSIM_PLATFORM_NONE,
	SOFTSIM_PLATFORM_QUALCOMM,
	SOFTSIM_PLATFORM_MEDIATEK,
	SOFTSIM_PLATFORM_MAX,
	SOFTSIM_PLATFORM_END = 0xff
}SoftsimPlatformType;

typedef enum
{
	SOFTSIM_TYPE_NONE,
	SOFTSIM_TYPE_LOCAL_SIM,
	SOFTSIM_TYPE_REMOTE_SIM,
	SOFTSIM_TYPE_MAX,
	SOFTSIM_TYPE_END = 0xff
}SoftsimType;

typedef enum
{
	SOFTSIM_PHYSICAL_SIM_CHANNEL,
	SOFTSIM_VIRTUAL_SIM_CHANNEL,
	SOFTSIM_CHANNEL_MAX,
	SOFTSIM_CHANNEL_END = 0xff
}SoftsimChannelType;


typedef enum {
	SOFTSIM_IPVER_IPV4 = 4,
	SOFTSIM_IPVER_IPV6 = 6,
	SOFTSIM_IPVER_MAX = 0x1fffffff
}SoftsimIpVersion;

typedef enum {
	SOFTSIM_IP_PROTOCOL_ICMP = 1,
	SOFTSIM_IP_PROTOCOL_TCP = 6,
	SOFTSIM_IP_PROTOCOL_UDP = 17,
	SOFTSIM_IP_PROTOCOL_GRE = 47,
	SOFTSIM_IP_PROTOCOL_MAX = 0x1fffffff
}SoftsimIpProtocol;



#ifdef __cplusplus
		}
#endif

#endif /*__SOFTSIM_ENUM_H__*/



